version: "3.7"
services:
    speedtestapi:
        build:
            context: .

        healthcheck:
            test: ["CMD-SHELL", "node healthcheck.js"]
            interval: 10s
            timeout: 5s
            retries: 5

        depends_on:
            postgres:
                condition: service_healthy

        networks:
            - default

        restart: always

        ports:
            - 80

    postgres:
        image: postgres:12.2-alpine

        healthcheck:
            interval: 10s
            timeout: 5s
            retries: 5

        networks:
            - default

        volumes:
            - ./databaseEntrypoint:/docker-entrypoint-initdb.d
            - speedtestApiPostgresqlData:/var/lib/postgresql/data

        environment:
            PGDATA: '/var/lib/postgresql/data/pgdata'

volumes:
    speedtestApiPostgresqlData:
        driver: local