# not sure to do this yet. Will work on this
version: "3.7"
services:
    speedtestapi:
        build:
            dockerfile: Dockerfile.production

        container_name: speedtestApiProd

    postgres:
        container_name: speedtestApiPostgresqlProd

        environment:
            POSTGRES_USER: ${PG_USER-speedtestApiProd}
            POSTGRES_PASSWORD: ${PG_PASSWORD:?Missing environment variable see readme}
            POSTGRES_DB: ${PG_DB-speedtestApiProd}