version: "3.7"
# Prod setup
services:
    speedtestapi:
        build:
            context: .

        networks:
            - default

        restart: always

        ports:
            - 80

    postgres:
        image: postgres:12.2-alpine

        networks:
            - default

        volumes:
            - ./databaseEntrypoint:/docker-entrypoint-initdb.d
            - speedtestApiPostgresqlData:/var/lib/postgresql/data

        environment:
            PGDATA: '/var/lib/postgresql/data/pgdata'

volumes:
    speedtestApiPostgresqlData:
        driver: local